openapi: 3.0.0
info:
  title: Football Competition Management API
  version: 1.0.0
  description: API for managing football competitions, teams, and players.
servers:
  - url: http://api.example.com/v1
paths:

components:
  schemas:

