openapi: 3.0.0
info:
  title: Football Competition Management API
  version: 1.0.0
  description: API for managing football competitions, teams, and players.
servers:
  - url: http://api.example.com/v1
paths:

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
          example: LIGA
        location:
          type: string
          example: ESPAGNE or EUROPE

    Team:
      type: object
      properties:
        name:
          type: string
          example: Real Madrid
        slogan:
          type: string
          example: Hala Madrid
        competitions:
          type: array
          items:
            $ref: '#/components/schemas/Competition'
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'

    Player:
      type: object
      properties:
        name:
          type: string
          example: Cristiano Ronaldo
        number:
          type: integer
          example: 7
        strongFoot:
          type: string
          enum: [Left, Right]
          example: Right


